export const SHOW_LOGIN_MODAL = 'DISPLAY_LOGIN_MODAL'
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL'
export const IS_CONNECTED = 'IS_CONNECTED'
export const SUBMIT_REGISTER_FORM = 'SUBMIT_REGISTER_FORM'